altliebe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('messaging/', include('messaging.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .views import (
    index,
    ProductList,
    ProductDetail,
    ProductCreate,
    ProductUpdate,
    ProductDelete,
    AddToWishlistView,
    wishlist_view,
    RemoveFromWishlistView
)
from users.views import profile_view
from messaging.views import StartConversationView, ConversationDetail


urlpatterns = [
    path('', index, name='home'),
    path('products/', ProductList.as_view(), name='product-list'),
    path('products/add/', ProductCreate.as_view(), name='product-create'),
    path('products/<slug:slug>/',
         ProductDetail.as_view(), name='product-detail'),
    path('products/<slug:slug>/edit/',
         ProductUpdate.as_view(), name='product-update'),
    path('products/<slug:slug>/delete/',
         ProductDelete.as_view(), name='product-delete'),
    path('add-to-wishlist/<int:product_id>/',
         AddToWishlistView.as_view(), name='add-to-wishlist'),
    path('wishlist/', wishlist_view, name='wishlist-view'),
    path('wishlist/remove/<int:product_id>/',
         RemoveFromWishlistView.as_view(), name='wishlist-remove'),
    path('messaging/start/<slug:product_slug>/',
         StartConversationView.as_view(),
         name='start_conversation'),
    path('messaging/conversation/<int:conversation_id>/',
         ConversationDetail.as_view(),
         name='conversation_detail'),
]

users/urls.py
from django.urls import path
from .models import Profile
from .views import (
    register,
    CustomLoginView,
    profile_view,
    ProfileUpdate,
    AccountDelete
)
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('register/',register, name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('profile/edit/', ProfileUpdate.as_view(), name='edit-profile'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),
    path('profile/<str:username>/', profile_view, name='user-profile'),
    path('delete-account/', AccountDelete.as_view(), name='delete-account'),
]

products/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
import logging


# Get an instance of a logger
logger = logging.getLogger(__name__)

# Choices Fields
CATEGORY = (
    (0, "Electronics"),
    (1, "Fashion and Apparel"),
    (2, "Home and Garden"),
    (3, "Sports and Outdoors"),
    (4, "Toys and Games"),
    (5, "Books and Media"),
    (6, "Pet Supplies"),
    (7, "Others"),
)

AVAILABILITY = (
    (0, "available"), (1, "reserved"), (2, "sold")
)

STATUS = (
    (0, "used"), (1, "new"), (2, "handmade")
)

# Create your models here.


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    featured_image = CloudinaryField(
        'image', default='static/images/product-default-image.jpg')
    category = models.IntegerField(choices=CATEGORY, default=0)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    seller = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="products")
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    availability = models.IntegerField(choices=AVAILABILITY, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, related_name='images', on_delete=models.CASCADE)
    image = CloudinaryField('image')

    def __str__(self):
        return f"Image for {self.product.title}"


class Wishlist(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='wishlist')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='wished_by')
    added_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Prevent duplicate wishlist items for the same user
        unique_together = ('user', 'product')

    def __str__(self):
        return f"{self.user.username}'s wishlist"

products/forms.py
from django import forms
from .models import Product, ProductImage

# Choices Fields
CATEGORY = (
    (0, "Electronics"),
    (1, "Fashion and Apparel"),
    (2, "Home and Garden"),
    (3, "Sports and Outdoors"),
    (4, "Toys and Games"),
    (5, "Books and Media"),
    (6, "Pet Supplies"),
    (7, "Others")
)
STATUS = (
    (0, "used"), (1, "new"), (2, "handmade")
)

class ProductSearchForm(forms.Form):
    query = forms.CharField(
        required=False,
        label='',
        widget=forms.TextInput(attrs={'placeholder': 'What Are You Looking For'})
    )

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'featured_image', 'description', 'category', 'price', 'status', 'availability']


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image']

products/views.py
from django.db import IntegrityError, transaction
from django.db.models import Q
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic, View
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DetailView,
    DeleteView
)
from django.urls import reverse_lazy, reverse
from django.forms import inlineformset_factory
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from .models import Product, ProductImage, CATEGORY, STATUS, Wishlist
from .forms import ProductForm, ProductSearchForm, ProductImageForm
from users.models import Profile
from messaging.models import Conversation, Message
from django.contrib import messages
import logging


User = get_user_model()
logger = logging.getLogger(__name__)


def my_function():
    logger.debug('This is a debug message')


# Create the formset class
ProductImageFormSet = inlineformset_factory(
    Product,
    ProductImage,
    form=ProductImageForm,
    extra=5,
    max_num=5,
    can_delete=True
)


# Create your views here.
def index(request):
    return render(request, 'products/index.html')


class ProductList(generic.ListView):
    model = Product
    template_name = "products/product_list.html"
    context_object_name = 'products'
    paginate_by = 6

    def get_queryset(self):
        queryset = Product.objects.filter(
            Q(availability=0) | Q(availability=1))
        query = self.request.GET.get('query', '').strip()

        # Using lambda to filter tuples for category and status search
        category_search = list(
             filter(lambda x: x[1].startswith(query), CATEGORY))
        status_search = list(filter(lambda x: x[1].startswith(query), STATUS))

        # Extracting the first element (value) from the filtered tuples
        category_search = category_search[0][0] if category_search else -1
        status_search = status_search[0][0] if status_search else -1

        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(description__icontains=query) |
                Q(seller__username__icontains=query) |
                Q(city__icontains=query) |
                Q(state__icontains=query) |
                Q(category__in=[category_search]) |
                Q(status__in=[status_search])
            )

        category = self.request.GET.get('category', '')
        status = self.request.GET.get('status', '')

        if category:
            queryset = queryset.filter(category=category)

        if status:
            queryset = queryset.filter(status=status)

        # Sorting logic
        sort = self.request.GET.get('sort', 'date_desc')
        if sort == 'price_asc':
            queryset = queryset.order_by('price')
        elif sort == 'price_desc':
            queryset = queryset.order_by('-price')
        elif sort == 'date_asc':
            queryset = queryset.order_by('created_at')
        elif sort == 'date_desc':
            queryset = queryset.order_by('-created_at')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Pass the search form to the template
        context['form'] = ProductSearchForm(self.request.GET or None)
        return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'products/product_detail.html'

    def get_queryset(self):
        """Ensure only available products can be viewed."""
        return super().get_queryset().all()

    def post(self, request, *args, **kwargs):
        # Get the product
        self.object = self.get_object()
        conversation, _ = Conversation.objects.get_or_create(
            product=self.object)

        message_text = request.POST.get('message')
        if message_text:
            Message.objects.create(
                conversation=conversation,
                sender=request.user,
                text=message_text
            )
            # Redirect to the product detail page after posting the message
            return HttpResponseRedirect(self.object.get_absolute_url())
        else:
            # Handle the case where message is not valid
            context = self.get_context_data()
            context['error'] = 'Message text cannot be empty.'
            return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        context['product'] = product
        conversations = Conversation.objects.filter(
             product=product).order_by('-created_at')
        context['conversations'] = conversations
        return context


# Product Create View
class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_create.html'
    success_url = reverse_lazy('product-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'formset' not in context:
            context['formset'] = ProductImageFormSet()
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        formset = ProductImageFormSet(request.POST, request.FILES)

        if form.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    # Set the seller to the current user
                    form.instance.seller = request.user
                    # Now the self.object will have the newly created object
                    self.object = form.save()

                    # Set the instance of the formset and save
                    formset.instance = self.object
                    formset.save()

                return super().form_valid(form)

            except IntegrityError:
                # Handle error when a newly added product has the same title
                messages.error(
                    request,
                    'A product with this title already exists. Please choose a different one!')
                return self.render_to_response(
                    self.get_context_data(form=form, formset=formset))

        return self.render_to_response(
            self.get_context_data(form=form, formset=formset))

    def form_valid(self, form):
        """ This method is what sets self.object = form.save() """
        response = super().form_valid(form)
        # form_valid should not be called if the form is not valid
        return response


class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    fields = [
        'title',
        'featured_image',
        'category',
        'description',
        'price',
        'status',
        'availability'
    ]

    template_name = 'products/product_form.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    success_url = reverse_lazy('product-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = ProductImageFormSet(
                self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = ProductImageFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        # This ensures formset is accessible in this method
        formset = context['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save(commit=False)
            self.object.seller = self.request.user
            self.object.city = self.request.user.profile.city
            self.object.state = self.request.user.profile.state
            self.object.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        return self.render_to_response(context)


class ProductDelete(DeleteView):
    model = Product
    template_name = 'products/product_confirm_delete.html'
    # Redirect to product list view after deletion
    success_url = reverse_lazy('product-list')


class AddToWishlistView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        product_id = kwargs.get('product_id')
        product = get_object_or_404(Product, id=product_id)

        # Check if the product is owned by the user
        if product.seller == request.user:
            messages.error(
                request, "You cannot add your own product to the wishlist.")
            return HttpResponseRedirect(reverse(
                'product-detail', kwargs={'slug': product.slug}))

        # Proceed to add to wishlist if it's not the user's own product
        Wishlist.objects.get_or_create(user=request.user, product=product)
        messages.success(request, "Product added to your wishlist.")
        return HttpResponseRedirect(reverse('product-detail', kwargs={'slug': product.slug}))


@login_required
def wishlist_view(request):
    # Get the wishlist items for the current user
    wishlist_items = Wishlist.objects.filter(
        user=request.user).select_related('product')

    return render(request, 'products/wishlist.html', {'wishlist_items': wishlist_items})


class RemoveFromWishlistView(LoginRequiredMixin, View):
    def post(self, request, product_id):
        # Get the product and remove it from the user's wishlist
        product = get_object_or_404(Product, id=product_id)
        Wishlist.objects.filter(user=request.user, product=product).delete()
        return redirect('wishlist-view')

products/templates/products/index.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<!-- Custom CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'products/css/index.css' %}">
{% endblock %}

{% block content %}
<!-- Alert Section -->
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}

<!-- Gallery Container -->
<div class="container custom-container gallery-container">
    <h1 class="text-center">AltLiebe</h1>
    <div class="row">
        <!-- Image container -->
        <div class="col-md-4 image-container">
            <a href="{% url 'product-list' %}?category=0">
                <img src="{% static 'products/images/electronics.jpg' %}" alt="Electronics image">
                <div class="image-caption">Electronics</div>
            </a>
        </div>
        <div class="col-md-4 image-container">
            <a href="{% url 'product-list' %}?category=1">
                <img src="{% static 'products/images/fashion.jpg' %}" alt="Fashion image">
                <div class="image-caption">Fashion and Apparel</div>
            </a>
        </div>
        <div class="col-md-4 image-container">
            <a href="{% url 'product-list' %}?category=2">
                <img src="{% static 'products/images/home&garden.jpg' %}" alt="Home image">
                <div class="image-caption">Home and Garden</div>
            </a>
        </div>
    </div>

    <!-- Second row of images -->
    <div class="row">
        <div class="col-md-4 image-container">
            <a href="{% url 'product-list' %}?category=3">
                <img src="{% static 'products/images/sports&outdoors.jpg' %}" alt="Sport-gears image">
                <div class="image-caption">Sports and Outdoors</div>
            </a>
        </div>
        <div class="col-md-4 image-container">
            <a href="{% url 'product-list' %}?category=4">
                <img src="{% static 'products/images/toys&games.jpg' %}" alt="Toys image">
                <div class="image-caption">Toys and Games</div>
            </a>
        </div>
        <div class="col-md-4 image-container">
            <a href="{% url 'product-list' %}?category=5">
                <img src="{% static 'products/images/books.jpg' %}" alt="Books image">
                <div class="image-caption">Books and Media</div>
            </a>
        </div>
    </div>

    <!-- Third row of images with last two cards centered -->
<div class="row" id="last-row">
    <div class="col-md-4 col-md-offset-2 col-md-push-4 image-container">
        <a href="{% url 'product-list' %}?category=6">
            <img src="{% static 'products/images/pet-supplies.jpg' %}" alt="Pet Supplies image">
            <div class="image-caption">Pet Supplies</div>
        </a>
    </div>
    <div class="col-md-4 image-container">
        <a href="{% url 'product-list' %}?category=7">
            <img src="{% static 'products/images/others.png' %}" alt="Other products image">
            <div class="image-caption">Others</div>
        </a>
    </div>
</div>
</div>
{% endblock %}

products/templates/products/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Are you sure you want to delete "{{ object }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" value="submit" class="btn btn-danger">Yes, delete it</button>
        <a href="{% url 'product-list' %}" class="btn btn-secondary" aria-label="Cancel">Cancel</a>
    </form>
</div>
{% endblock %}

products/templates/products/product_create.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<!-- Custom CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'products/css/product_create.css' %}">
{% endblock %}

{% block content %}

<!-- Alert Messages -->
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}

<!-- Display non-field errors for the form -->
{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
</div>
{% endif %}

<!-- Display errors for individual fields in the form -->
{% for field in form %}
{% if field.errors %}
<div class="alert alert-danger" role="alert">
    {{ field.label }}: {{ field.errors }}
</div>
{% endif %}
{% endfor %}

<!-- Display non-form errors for the formset -->
{% if formset.non_form_errors %}
<div class="alert alert-danger" role="alert">
    {{ formset.non_form_errors }}
</div>
{% endif %}

<!-- Display errors for individual fields in the formset -->
{% for form in formset %}
{% for field in form %}
{% if field.errors %}
<div class="alert alert-danger" role="alert">
    {{ field.label }}: {{ field.errors }}
</div>
{% endif %}
{% endfor %}
{% endfor %}

<!-- Add Product Form -->
<div class="product-container mt-5">
    <div class="card">
        <div class="card-header bg-primary text-white">
            <h2>Add New Product</h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <!--  Title Field -->
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input type="text" class="form-control" id="id_title" name="title"
                        placeholder="Enter product title" required>
                        {{ form.title.errors }}
                </div>

                <!-- Featured Image Upload Section -->
                <div class="form-group">
                    <label for="id_featured_image">Main Image</label>
                    <input type="file" class="form-control-file" id="id_featured_image" name="featured_image">
                    <div id="featured_image_preview" class="image-preview">
                        <img class="card-img-top" src="{{ product.featured_image.url }}" alt="{{ product.title }}">
                    </div>
                    {{ form.featured_image.errors }}
                </div>


                <!-- Additional Images Upload Section -->
                <label>Additional Images</label>
                {{ formset.management_form }}
                <div id="additional_images_preview" class="row">
                    {% for form in formset %}
                    <div class="col-sm-3 additional-image">
                        {{ form.image }}
                        <div class="image-preview">
                            <img id="img_preview_{{ forloop.counter0 }}" class="img-fluid img-thumbnail" alt="image thumbnail"/>
                        </div>
                        {{ form.image.errors }}
                    </div>
                    {% endfor %}
                </div>

                <!-- Category Field -->
                <div class="form-group">
                    <label for="id_category">Category</label>
                    <select class="form-control" id="id_category" name="category">
                        <option value="0">Electronics</option>
                        <option value="1">Fashion and Apparel</option>
                        <option value="2">Home and Garden</option>
                        <option value="3">Sports and Outdoors</option>
                        <option value="4">Toys and Games</option>
                        <option value="5">Books and Media</option>
                        <option value="6">Pet Supplies</option>
                        <option value="7">Other</option>
                    </select>
                </div>

                <!-- Description Field -->
                <div class="form-group">
                    <label for="id_description">Description</label>
                    <textarea class="form-control" id="id_description" name="description" rows="3"
                        placeholder="Enter product description"></textarea>
                </div>

                <!-- Price Field -->
                <div class="form-group">
                    <label for="id_price">Price</label>
                    <div class="input-group">
                        <input type="text" pattern="[0-9]+([,\.][0-9]{1,2})?" step="0.10" class="form-control"
                            id="id_price" name="price" placeholder="0.00" required>
                        <div class="input-group-append">
                            <span class="input-group-text">€</span>
                        </div>
                    </div>
                </div>

                <!-- Status Field -->
                <div class="form-group">
                    <label for="id_status">Status</label>
                    <select class="form-control" id="id_status" name="status">
                        <option value="0">Used</option>
                        <option value="1">New</option>
                        <option value="2">Handmade</option>
                    </select>
                </div>

                <!--  Avalibility Field -->
                <div class="form-group">
                    <label for="id_status">Availability</label>
                    <select class="form-control" id="id_status" name="availability">
                        <option value="0">Available</option>
                        <option value="1">Reserved</option>
                        <option value="2">Sold</option>
                    </select>
                </div>

                <!-- Form Controls -->
                <div class="form-group d-flex justify-content-between align-items-center mt-4">
                    <button type="submit" class="btn btn-success">Submit</button>
                    <a href="{% url 'product-list' %}" class="btn btn-secondary" aria-label="cancel">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}
<script src="{% static 'products/js/product_create.js' %}"></script>
{% endblock %}

products/templates/products/product_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Edit Product</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <fieldset>
            <legend>Product Images</legend>
            {{ formset.management_form }}
            {% for form in formset %}
            {{ form.as_p }}
            {% endfor %}
        </fieldset>
        <button type="submit" class="btn btn-primary" value="update">Update</button>
        <a href="{% url 'product-list' %}" class="btn btn-secondary" aria-label="cancel">Cancel</a>
    </form>
</div>
{% endblock %}

products/templates/products/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'products/css/products-style.css' %}">

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show"
    role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert"
        aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}

<!-- Sorting Options -->
<div class="sorting-options text-center mb-3">
    <a href="?sort=price_asc"
        class="btn btn-outline-primary {% if request.GET.sort == 'price_asc' %}active{% endif %}">Price
        Low to High</a>
    <a href="?sort=price_desc"
        class="btn btn-outline-primary {% if request.GET.sort == 'price_desc' %}active{% endif %}">Price
        High to Low</a>
    <a href="?sort=date_asc"
        class="btn btn-outline-primary {% if request.GET.sort == 'date_asc' %}active{% endif %}">Oldest
        First</a>
    <a href="?sort=date_desc"
        class="btn btn-outline-primary {% if request.GET.sort == 'date_desc' %}active{% endif %}">Newest
        First</a>
</div>

<!-- Product Listing -->
<section>
    <div class="container">
        <div class="row">
            {% for product in products %}
            <div class="col-md-6">
                <div class="product-card">
                    <div class="image-container">
                        <img src="{{ product.featured_image.url }}"
                            alt="{{ product.title }}" class="img-fluid">
                    </div>
                    <h2><a href="{% url 'product-detail' product.slug %}">
                        {{ product.title }}</a></h2>
                    <p>Category: {{ product.get_category_display }}</p>
                    <p>{{ product.description }}</p>
                    <p>Price: {{ product.price }} €</p>
                    <p>Seller: <a
                            href="{% url 'user-profile' username=product.seller.username %}">
                            {{ product.seller.username }}</a></p>
                    {% if product.seller.profile.city or product.seller.profile.state %}
                    <p>Location: {{ product.seller.profile.city }},
                        {{ product.seller.profile.state }}</p>
                    {% else %}
                    <p>Location: Not Set</p>
                    {% endif %}
                    <p>Status: {{ product.get_status_display }}</p>
                    <p>Availability: {{ product.get_availability_display }}</p>
                    <p>Posted on: {{ product.created_at|date:"Y-m-d H:i" }}</p>
                </div>
            </div>
            {% empty %}
            <p>No products found.</p>
            {% endfor %}
</section>

<!-- Pagination Controls -->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <!-- With Ensurance that Sorting Persists with Pagination -->
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link"
                href="?page=1{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}">&laquo;
                First</a></li>
        <li class="page-item"><a class="page-link"
                href="?page={{ page_obj.previous_page_number }}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}">Previous</a>
        </li>
        {% endif %}
        <li class="page-item disabled"><span class="page-link">Page
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link"
                href="?page={{ page_obj.next_page_number }}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}">Next</a>
        </li>
        <li class="page-item"><a class="page-link"
                href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}">&raquo;
                Last</a></li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

products/templates/products/wishlist.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h2>My Wishlist</h2>
    {% for item in wishlist_items %}
    <div>
        <a href="{% url 'product-detail' slug=item.product.slug %}">
            {{item.product.title }}</a>
        <form action="{% url 'wishlist-remove' item.product.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Remove">
        </form>
    </div>
    {% empty %}
    <p>Your wishlist is empty.</p>
    {% endfor %}
</div>
{% endblock %}